CREATE DATABASE IF NOT EXISTS LMS;
CREATE DATABASE IF NOT EXISTS module_tuyendung;
CREATE DATABASE IF NOT EXISTS system_services;
CREATE DATABASE IF NOT EXISTS hpc_drive;
CREATE DATABASE IF NOT EXISTS hpc_dispatch;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
